source 'https://rubygems.org'

gem 'sinatra'
gem 'multi_json'
gem "omniauth-agsquared-oauth2", :git => "git@github.com:farmersweb/omniauth-agsquared-oauth2.git", :branch => "master", :ref => "c382862d2217d13a8c80b5b19d60538692aa2ff5"
gem 'agsquared-api-wrapper', :git => "git@github.com:farmersweb/agsquared-api-wrapper.git", :branch => "master"